/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.finalui.UI;

/**
 *
 * @author ducng
 */
public class addHistory extends javax.swing.JPanel {

    /**
     * Creates new form addHistory
     */
    public addHistory() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelStart = new javax.swing.JLabel();
        labelTimeStart = new javax.swing.JLabel();
        labelEnd = new javax.swing.JLabel();
        labelTimeEnd = new javax.swing.JLabel();
        inputStart = new javax.swing.JTextField();
        inputTimeStartDay = new javax.swing.JTextField();
        inputTimeStartMonth = new javax.swing.JTextField();
        inputTimeStartYear = new javax.swing.JTextField();
        inputEnd = new javax.swing.JTextField();
        inputTimeEndDay = new javax.swing.JTextField();
        inputTimeEndMonth = new javax.swing.JTextField();
        inputTimeEndYear = new javax.swing.JTextField();
        labelTinhTrang = new javax.swing.JLabel();
        inputTinhTrang = new javax.swing.JTextField();
        labelDauHieu = new javax.swing.JLabel();
        checkHo = new javax.swing.JRadioButton();
        checkSot = new javax.swing.JRadioButton();
        checkKhoTho = new javax.swing.JRadioButton();
        checkNone = new javax.swing.JRadioButton();
        labelTest = new javax.swing.JLabel();
        selectTest = new javax.swing.JComboBox<>();
        labelCachLy = new javax.swing.JLabel();
        selectCachLy = new javax.swing.JComboBox<>();
        listTiepXuc = new javax.swing.JLabel();
        labelName = new javax.swing.JLabel();
        labelID = new javax.swing.JLabel();
        labelTime = new javax.swing.JLabel();
        inputName = new javax.swing.JTextField();
        inputID = new javax.swing.JTextField();
        inputTimeTiepXuc = new javax.swing.JTextField();
        buttomSave = new javax.swing.JButton();
        buttomExit = new javax.swing.JButton();
        labelNumofTest = new javax.swing.JLabel();
        selectNumofTest = new javax.swing.JComboBox<>();
        labelXepLoai = new javax.swing.JLabel();
        selectXepLoai = new javax.swing.JComboBox<>();
        labelXepLoai2 = new javax.swing.JLabel();
        selectXepLoai2 = new javax.swing.JComboBox<>();
        labelNote = new javax.swing.JLabel();
        showNote = new javax.swing.JTextField();

        labelStart.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        labelStart.setText("Nơi xuất phát:");

        labelTimeStart.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        labelTimeStart.setText("Thời gian xuất phát");

        labelEnd.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        labelEnd.setText("Đích đến");

        labelTimeEnd.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        labelTimeEnd.setText("Thời gian đến:");

        inputStart.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        inputTimeStartDay.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        inputTimeStartDay.setText("dd");
        inputTimeStartDay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputTimeStartDayActionPerformed(evt);
            }
        });

        inputTimeStartMonth.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        inputTimeStartMonth.setText("mm");
        inputTimeStartMonth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputTimeStartMonthActionPerformed(evt);
            }
        });

        inputTimeStartYear.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        inputTimeStartYear.setText("yyyy");

        inputEnd.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        inputTimeEndDay.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        inputTimeEndDay.setText("dd");

        inputTimeEndMonth.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        inputTimeEndMonth.setText("mm");
        inputTimeEndMonth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputTimeEndMonthActionPerformed(evt);
            }
        });

        inputTimeEndYear.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        inputTimeEndYear.setText("yyyy");

        labelTinhTrang.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        labelTinhTrang.setText("Tình trạng sức khoẻ:");

        inputTinhTrang.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        labelDauHieu.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        labelDauHieu.setText("Dấu hiệu bất thường");

        checkHo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        checkHo.setText("Ho");
        checkHo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkHoActionPerformed(evt);
            }
        });

        checkSot.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        checkSot.setText("Sốt");

        checkKhoTho.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        checkKhoTho.setText("Khó thở");
        checkKhoTho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkKhoThoActionPerformed(evt);
            }
        });

        checkNone.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        checkNone.setText("Không");

        labelTest.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        labelTest.setText("Đã test Covid chưa:");

        selectTest.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        selectTest.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chưa", "Rồi" }));

        labelCachLy.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        labelCachLy.setText("Cách ly:");

        selectCachLy.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        selectCachLy.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Đã đủ 14 ngày", "Chưa đủ 14 ngày" }));

        listTiepXuc.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        listTiepXuc.setText("Danh sách tiếp xúc gần:");

        labelName.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        labelName.setText("Họ tên:");

        labelID.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        labelID.setText("Số CMND/CCCD:");

        labelTime.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        labelTime.setText("Thời gian tiếp xúc:");

        inputName.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        inputID.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        inputTimeTiepXuc.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        buttomSave.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        buttomSave.setIcon(new javax.swing.ImageIcon("D:\\Workspace\\JAVA\\MyApp\\src\\icon\\Paomedia-Small-N-Flat-Floppy-0.png")); // NOI18N
        buttomSave.setText("Lưu lại");
        buttomSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttomSaveActionPerformed(evt);
            }
        });

        buttomExit.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        buttomExit.setIcon(new javax.swing.ImageIcon("D:\\Workspace\\JAVA\\MyApp\\src\\icon\\Awicons-Vista-Artistic-Delete-0.png")); // NOI18N
        buttomExit.setText("Thoát");
        buttomExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttomExitActionPerformed(evt);
            }
        });

        labelNumofTest.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        labelNumofTest.setText("Số lần xét nghiệm:");

        selectNumofTest.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        selectNumofTest.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 lần", "2 lần", "3 lần", "4lần" }));

        labelXepLoai.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        labelXepLoai.setText("Xếp loại:");

        selectXepLoai.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        selectXepLoai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "F0", "F1", "F2", "F3", "F4", "F5" }));

        labelXepLoai2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        labelXepLoai2.setText("Xếp loại:");

        selectXepLoai2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        selectXepLoai2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "F0", "F1", "F2", "F3", "F4", "F5" }));

        labelNote.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        labelNote.setText("Ghi chú (nếu có):");

        showNote.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(showNote)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(labelDauHieu)
                        .addGap(18, 18, 18)
                        .addComponent(checkHo)
                        .addGap(27, 27, 27)
                        .addComponent(checkSot)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(checkKhoTho)
                        .addGap(18, 18, 18)
                        .addComponent(checkNone))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(labelEnd)
                        .addGap(18, 18, 18)
                        .addComponent(inputEnd))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(labelTinhTrang)
                        .addGap(18, 18, 18)
                        .addComponent(inputTinhTrang))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(labelTest)
                        .addGap(18, 18, 18)
                        .addComponent(selectTest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(labelCachLy)
                        .addGap(18, 18, 18)
                        .addComponent(selectCachLy, 0, 1, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(labelName)
                        .addGap(18, 18, 18)
                        .addComponent(inputName))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(labelID)
                        .addGap(18, 18, 18)
                        .addComponent(inputID))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(labelStart)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(inputStart))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(buttomSave)
                                    .addGap(18, 18, 18)
                                    .addComponent(buttomExit))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(labelNumofTest)
                                        .addGap(18, 18, 18)
                                        .addComponent(selectNumofTest, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(labelXepLoai)
                                        .addGap(18, 18, 18)
                                        .addComponent(selectXepLoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(listTiepXuc)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(labelTimeStart)
                                        .addGap(18, 18, 18)
                                        .addComponent(inputTimeStartDay, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(inputTimeStartMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(inputTimeStartYear, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(labelTimeEnd)
                                        .addGap(18, 18, 18)
                                        .addComponent(inputTimeEndDay, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(inputTimeEndMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(inputTimeEndYear, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(labelTime)
                                        .addGap(18, 18, 18)
                                        .addComponent(inputTimeTiepXuc, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(labelXepLoai2)
                                        .addGap(18, 18, 18)
                                        .addComponent(selectXepLoai2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(labelNote))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelStart)
                    .addComponent(inputStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTimeStart)
                    .addComponent(inputTimeStartDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputTimeStartMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputTimeStartYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelEnd)
                    .addComponent(inputEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTimeEnd)
                    .addComponent(inputTimeEndDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputTimeEndMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputTimeEndYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTinhTrang)
                    .addComponent(inputTinhTrang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDauHieu)
                    .addComponent(checkHo)
                    .addComponent(checkSot)
                    .addComponent(checkKhoTho)
                    .addComponent(checkNone))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTest)
                    .addComponent(selectTest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCachLy)
                    .addComponent(selectCachLy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNumofTest)
                    .addComponent(selectNumofTest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelXepLoai)
                    .addComponent(selectXepLoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addComponent(listTiepXuc)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelName))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelID)
                    .addComponent(inputID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTime)
                    .addComponent(inputTimeTiepXuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelXepLoai2)
                    .addComponent(selectXepLoai2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(labelNote)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(showNote, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(buttomSave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttomExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void inputTimeStartDayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputTimeStartDayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputTimeStartDayActionPerformed

    private void inputTimeStartMonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputTimeStartMonthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputTimeStartMonthActionPerformed

    private void inputTimeEndMonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputTimeEndMonthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputTimeEndMonthActionPerformed

    private void checkHoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkHoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkHoActionPerformed

    private void checkKhoThoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkKhoThoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkKhoThoActionPerformed

    private void buttomExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttomExitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttomExitActionPerformed

    private void buttomSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttomSaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttomSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttomExit;
    private javax.swing.JButton buttomSave;
    private javax.swing.JRadioButton checkHo;
    private javax.swing.JRadioButton checkKhoTho;
    private javax.swing.JRadioButton checkNone;
    private javax.swing.JRadioButton checkSot;
    private javax.swing.JTextField inputEnd;
    private javax.swing.JTextField inputID;
    private javax.swing.JTextField inputName;
    private javax.swing.JTextField inputStart;
    private javax.swing.JTextField inputTimeEndDay;
    private javax.swing.JTextField inputTimeEndMonth;
    private javax.swing.JTextField inputTimeEndYear;
    private javax.swing.JTextField inputTimeStartDay;
    private javax.swing.JTextField inputTimeStartMonth;
    private javax.swing.JTextField inputTimeStartYear;
    private javax.swing.JTextField inputTimeTiepXuc;
    private javax.swing.JTextField inputTinhTrang;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelCachLy;
    private javax.swing.JLabel labelDauHieu;
    private javax.swing.JLabel labelEnd;
    private javax.swing.JLabel labelID;
    private javax.swing.JLabel labelName;
    private javax.swing.JLabel labelNote;
    private javax.swing.JLabel labelNumofTest;
    private javax.swing.JLabel labelStart;
    private javax.swing.JLabel labelTest;
    private javax.swing.JLabel labelTime;
    private javax.swing.JLabel labelTimeEnd;
    private javax.swing.JLabel labelTimeStart;
    private javax.swing.JLabel labelTinhTrang;
    private javax.swing.JLabel labelXepLoai;
    private javax.swing.JLabel labelXepLoai2;
    private javax.swing.JLabel listTiepXuc;
    private javax.swing.JComboBox<String> selectCachLy;
    private javax.swing.JComboBox<String> selectNumofTest;
    private javax.swing.JComboBox<String> selectTest;
    private javax.swing.JComboBox<String> selectXepLoai;
    private javax.swing.JComboBox<String> selectXepLoai2;
    private javax.swing.JTextField showNote;
    // End of variables declaration//GEN-END:variables
}
