/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.finalui.UI;

/**
 *
 * @author ducng
 */
public class detailForm extends javax.swing.JPanel {

    /**
     * Creates new form detailForm
     */
    public detailForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelChiTiet = new javax.swing.JLabel();
        labelID = new javax.swing.JLabel();
        fieldID = new javax.swing.JTextField();
        labelHoTen = new javax.swing.JLabel();
        fieldHoTen = new javax.swing.JTextField();
        labelHoKhau = new javax.swing.JLabel();
        labelQH = new javax.swing.JLabel();
        labelNgaySinh = new javax.swing.JLabel();
        labelGioiTinh = new javax.swing.JLabel();
        labelNoiSinh = new javax.swing.JLabel();
        labelNguyenQuan = new javax.swing.JLabel();
        labelDanToc = new javax.swing.JLabel();
        labelTonGiao = new javax.swing.JLabel();
        labelNgheNghiep = new javax.swing.JLabel();
        labelCMND = new javax.swing.JLabel();
        fieldHoKhau = new javax.swing.JTextField();
        fieldCMND = new javax.swing.JTextField();
        fieldNgaySinh = new javax.swing.JTextField();
        fieldGioiTinh = new javax.swing.JTextField();
        fieldNoiSinh = new javax.swing.JTextField();
        fieldNguyenQuan = new javax.swing.JTextField();
        fieldanToc = new javax.swing.JTextField();
        fieldQHChuHo = new javax.swing.JTextField();
        fieldTonGiao = new javax.swing.JTextField();
        fieldNgheNghiep = new javax.swing.JTextField();
        picture = new javax.swing.JPanel();
        labelGhiChu = new javax.swing.JLabel();
        jLog = new javax.swing.JScrollPane();
        ghichu = new javax.swing.JTextArea();
        exit = new javax.swing.JButton();

        labelChiTiet.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        labelChiTiet.setText("Thông tin chi tiết");

        labelID.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        labelID.setText("ID");

        fieldID.setEditable(false);
        fieldID.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        labelHoTen.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        labelHoTen.setText("Họ tên");

        fieldHoTen.setEditable(false);
        fieldHoTen.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        labelHoKhau.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        labelHoKhau.setText("Hộ khẩu");

        labelQH.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        labelQH.setText("Quan hệ với chủ hộ");

        labelNgaySinh.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        labelNgaySinh.setText("Ngày sinh");

        labelGioiTinh.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        labelGioiTinh.setText("Giới tính");

        labelNoiSinh.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        labelNoiSinh.setText("Nơi sinh");

        labelNguyenQuan.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        labelNguyenQuan.setText("Nguyên quán");
        labelNguyenQuan.setToolTipText("");

        labelDanToc.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        labelDanToc.setText("Dân tộc");

        labelTonGiao.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        labelTonGiao.setText("Tôn giáo");

        labelNgheNghiep.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        labelNgheNghiep.setText("Nghề nghiệp");

        labelCMND.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        labelCMND.setText("CMND");

        fieldHoKhau.setEditable(false);
        fieldHoKhau.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        fieldCMND.setEditable(false);
        fieldCMND.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        fieldNgaySinh.setEditable(false);
        fieldNgaySinh.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        fieldGioiTinh.setEditable(false);
        fieldGioiTinh.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        fieldNoiSinh.setEditable(false);
        fieldNoiSinh.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        fieldNguyenQuan.setEditable(false);
        fieldNguyenQuan.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        fieldanToc.setEditable(false);
        fieldanToc.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        fieldQHChuHo.setEditable(false);
        fieldQHChuHo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        fieldTonGiao.setEditable(false);
        fieldTonGiao.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        fieldNgheNghiep.setEditable(false);
        fieldNgheNghiep.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        picture.setBackground(new java.awt.Color(204, 255, 0));

        javax.swing.GroupLayout pictureLayout = new javax.swing.GroupLayout(picture);
        picture.setLayout(pictureLayout);
        pictureLayout.setHorizontalGroup(
            pictureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 145, Short.MAX_VALUE)
        );
        pictureLayout.setVerticalGroup(
            pictureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 161, Short.MAX_VALUE)
        );

        labelGhiChu.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        labelGhiChu.setText("Ghi chú");

        ghichu.setColumns(20);
        ghichu.setRows(5);
        jLog.setViewportView(ghichu);

        exit.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        exit.setText("Thoát");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelNguyenQuan)
                        .addGap(18, 18, 18)
                        .addComponent(fieldNguyenQuan))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelChiTiet, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelNgaySinh)
                                .addGap(18, 18, 18)
                                .addComponent(fieldNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(labelHoKhau)
                                        .addGap(10, 10, 10)
                                        .addComponent(fieldHoKhau))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(labelID)
                                        .addGap(18, 18, 18)
                                        .addComponent(fieldID, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(labelHoTen)
                                    .addComponent(labelCMND))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(fieldHoTen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fieldCMND, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(labelGioiTinh)
                                        .addGap(18, 18, 18)
                                        .addComponent(fieldGioiTinh))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(labelNgheNghiep)
                                        .addGap(18, 18, 18)
                                        .addComponent(fieldNgheNghiep)
                                        .addGap(18, 18, 18)
                                        .addComponent(labelTonGiao))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(labelQH)
                                        .addGap(18, 18, 18)
                                        .addComponent(fieldQHChuHo, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(labelDanToc)
                                        .addGap(18, 18, 18)
                                        .addComponent(fieldanToc, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(fieldTonGiao))))
                        .addGap(18, 18, 18)
                        .addComponent(picture, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(labelNoiSinh)
                        .addGap(29, 29, 29)
                        .addComponent(fieldNoiSinh))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelGhiChu)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLog))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(exit)
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelChiTiet)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fieldHoTen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(labelID)
                                .addComponent(fieldID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(labelHoTen)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelHoKhau)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(fieldHoKhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(labelCMND)
                                .addComponent(fieldCMND, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelNgaySinh)
                            .addComponent(labelGioiTinh)
                            .addComponent(fieldNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fieldGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelQH)
                            .addComponent(labelDanToc)
                            .addComponent(fieldanToc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fieldQHChuHo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(picture, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNgheNghiep)
                    .addComponent(labelTonGiao)
                    .addComponent(fieldTonGiao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldNgheNghiep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNoiSinh)
                    .addComponent(fieldNoiSinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNguyenQuan)
                    .addComponent(fieldNguyenQuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(labelGhiChu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLog, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(exit)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public javax.swing.JButton getExit() {
        return exit;
    }

    public javax.swing.JTextField getFieldCMND() {
        return fieldCMND;
    }

    public javax.swing.JTextField getFieldGioiTinh() {
        return fieldGioiTinh;
    }

    public javax.swing.JTextField getFieldHoKhau() {
        return fieldHoKhau;
    }

    public javax.swing.JTextField getFieldHoTen() {
        return fieldHoTen;
    }

    public javax.swing.JTextField getFieldID() {
        return fieldID;
    }

    public javax.swing.JTextField getFieldNgaySinh() {
        return fieldNgaySinh;
    }

    public javax.swing.JTextField getFieldNgheNghiep() {
        return fieldNgheNghiep;
    }

    public javax.swing.JTextField getFieldNguyenQuan() {
        return fieldNguyenQuan;
    }

    public javax.swing.JTextField getFieldNoiSinh() {
        return fieldNoiSinh;
    }

    public javax.swing.JTextField getFieldQHChuHo() {
        return fieldQHChuHo;
    }

    public javax.swing.JTextField getFieldTonGiao() {
        return fieldTonGiao;
    }

    public javax.swing.JTextField getFieldDanToc() {
        return fieldanToc;
    }

    public javax.swing.JTextArea getGhichu() {
        return ghichu;
    }

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_exitActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exit;
    private javax.swing.JTextField fieldCMND;
    private javax.swing.JTextField fieldGioiTinh;
    private javax.swing.JTextField fieldHoKhau;
    private javax.swing.JTextField fieldHoTen;
    private javax.swing.JTextField fieldID;
    private javax.swing.JTextField fieldNgaySinh;
    private javax.swing.JTextField fieldNgheNghiep;
    private javax.swing.JTextField fieldNguyenQuan;
    private javax.swing.JTextField fieldNoiSinh;
    private javax.swing.JTextField fieldQHChuHo;
    private javax.swing.JTextField fieldTonGiao;
    private javax.swing.JTextField fieldanToc;
    private javax.swing.JTextArea ghichu;
    private javax.swing.JScrollPane jLog;
    private javax.swing.JLabel labelCMND;
    private javax.swing.JLabel labelChiTiet;
    private javax.swing.JLabel labelDanToc;
    private javax.swing.JLabel labelGhiChu;
    private javax.swing.JLabel labelGioiTinh;
    private javax.swing.JLabel labelHoKhau;
    private javax.swing.JLabel labelHoTen;
    private javax.swing.JLabel labelID;
    private javax.swing.JLabel labelNgaySinh;
    private javax.swing.JLabel labelNgheNghiep;
    private javax.swing.JLabel labelNguyenQuan;
    private javax.swing.JLabel labelNoiSinh;
    private javax.swing.JLabel labelQH;
    private javax.swing.JLabel labelTonGiao;
    private javax.swing.JPanel picture;
    // End of variables declaration//GEN-END:variables
}
