/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.finalui.UI;

/**
 *
 * @author ducng
 */
public class HomeLogin extends javax.swing.JPanel {

    /**
     * Creates new form HomeLogin
     */
    public HomeLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        leftPanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        labelPassword = new javax.swing.JLabel();
        labelSignIn = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        inputPassword = new javax.swing.JPasswordField();
        inputUsername = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        labelUsername = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        buttomLogin = new javax.swing.JButton();
        buttomForgot = new javax.swing.JButton();

        setBackground(new java.awt.Color(36, 47, 65));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        leftPanel.setBackground(new java.awt.Color(97, 212, 195));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Wellcome to HUST");

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("One love, one future");

        jLabel8.setIcon(new javax.swing.ImageIcon("D:\\Workspace\\JAVA\\MyApp\\src\\icon\\tải xuống.png")); // NOI18N

        javax.swing.GroupLayout leftPanelLayout = new javax.swing.GroupLayout(leftPanel);
        leftPanel.setLayout(leftPanelLayout);
        leftPanelLayout.setHorizontalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftPanelLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(leftPanelLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(22, 22, 22)
                        .addComponent(jLabel5))
                    .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, leftPanelLayout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        leftPanelLayout.setVerticalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, leftPanelLayout.createSequentialGroup()
                .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(leftPanelLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel5))
                    .addGroup(leftPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
        );

        add(leftPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 460));

        labelPassword.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        labelPassword.setForeground(new java.awt.Color(255, 255, 255));
        labelPassword.setText("Password");
        add(labelPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 160, 171, 40));

        labelSignIn.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        labelSignIn.setForeground(new java.awt.Color(255, 255, 255));
        labelSignIn.setText("Sign in");
        add(labelSignIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 10, 60, 50));
        add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 160, 260, 10));

        inputPassword.setBackground(new java.awt.Color(36, 47, 65));
        inputPassword.setForeground(new java.awt.Color(255, 255, 255));
        inputPassword.setText("jPasswordField1");
        inputPassword.setBorder(null);
        inputPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputPasswordActionPerformed(evt);
            }
        });
        add(inputPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 200, 260, 20));

        inputUsername.setBackground(new java.awt.Color(36, 47, 65));
        inputUsername.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        inputUsername.setForeground(new java.awt.Color(255, 255, 255));
        inputUsername.setText("Username");
        inputUsername.setBorder(null);
        inputUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputUsernameActionPerformed(evt);
            }
        });
        add(inputUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 140, 260, 20));
        add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 50, 189, 10));

        labelUsername.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        labelUsername.setForeground(new java.awt.Color(255, 255, 255));
        labelUsername.setText("Username:");
        add(labelUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 100, 171, 40));
        add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 220, 260, 10));

        buttomLogin.setBackground(new java.awt.Color(36, 47, 65));
        buttomLogin.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        buttomLogin.setForeground(new java.awt.Color(255, 255, 255));
        buttomLogin.setText("Login");
        buttomLogin.setBorder(null);
        buttomLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttomLoginActionPerformed(evt);
            }
        });
        add(buttomLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 260, 80, 30));

        buttomForgot.setBackground(new java.awt.Color(36, 47, 65));
        buttomForgot.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        buttomForgot.setForeground(new java.awt.Color(255, 255, 255));
        buttomForgot.setText("Forgot password, click here.");
        buttomForgot.setBorder(null);
        buttomForgot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttomForgotActionPerformed(evt);
            }
        });
        add(buttomForgot, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 300, -1, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void inputPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputPasswordActionPerformed

    private void inputUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputUsernameActionPerformed

    private void buttomLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttomLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttomLoginActionPerformed

    private void buttomForgotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttomForgotActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttomForgotActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttomForgot;
    private javax.swing.JButton buttomLogin;
    private javax.swing.JPasswordField inputPassword;
    private javax.swing.JTextField inputUsername;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JLabel labelPassword;
    private javax.swing.JLabel labelSignIn;
    private javax.swing.JLabel labelUsername;
    private javax.swing.JPanel leftPanel;
    // End of variables declaration//GEN-END:variables
}
