/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.finalui.UI;

/**
 *
 * @author ducng
 */
public class SingleForm extends javax.swing.JPanel {

    /**
     * Creates new form SingleForm
     */
    public SingleForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelName = new javax.swing.JLabel();
        inputName = new javax.swing.JTextField();
        labelSex = new javax.swing.JLabel();
        selectSex = new javax.swing.JComboBox<>();
        ID = new javax.swing.JLabel();
        inputID = new javax.swing.JTextField();
        labelReligion = new javax.swing.JLabel();
        inputReligion = new javax.swing.JTextField();
        birthday = new javax.swing.JLabel();
        labelNation = new javax.swing.JLabel();
        inputDay = new javax.swing.JTextField();
        inputYear = new javax.swing.JTextField();
        inputMonth = new javax.swing.JTextField();
        inputNation = new javax.swing.JTextField();
        labelNoiSinh = new javax.swing.JLabel();
        inputNoiSinh = new javax.swing.JTextField();
        labelDiaChi = new javax.swing.JLabel();
        inputDiaChi = new javax.swing.JTextField();
        imagePanel = new javax.swing.JPanel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        panelChose = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        panelPicture = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        labelTinhTrang = new javax.swing.JLabel();
        selectTinhTrang = new javax.swing.JComboBox<>();
        labelCachLy = new javax.swing.JLabel();
        inputCachLy = new javax.swing.JTextField();
        labelThoiGianCachLy = new javax.swing.JLabel();
        inputTimeCachLy = new javax.swing.JTextField();
        labelMucDo = new javax.swing.JLabel();
        selectMucDo = new javax.swing.JComboBox<>();
        labelTest = new javax.swing.JLabel();
        selectTest = new javax.swing.JComboBox<>();
        labelHinhThuc = new javax.swing.JLabel();
        inputHinhThuc = new javax.swing.JTextField();
        labelTimeTest = new javax.swing.JLabel();
        inputTimeTest = new javax.swing.JTextField();
        labelKetQua = new javax.swing.JLabel();
        selectKetQua = new javax.swing.JComboBox<>();
        labelLichTrinh = new javax.swing.JLabel();
        showLichTriinh = new javax.swing.JTextField();
        buttomSave = new javax.swing.JButton();
        buttomAdd = new javax.swing.JButton();
        buttomView = new javax.swing.JButton();
        buttomExit = new javax.swing.JButton();

        labelName.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        labelName.setText("Họ tên:");

        inputName.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        labelSex.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        labelSex.setText("Giới tính");

        selectSex.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        selectSex.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ" }));

        ID.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        ID.setText("Số CMND/CCCD:");

        inputID.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        labelReligion.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        labelReligion.setText("Tôn giáo:");

        inputReligion.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        birthday.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        birthday.setText("Ngày sinh:");

        labelNation.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        labelNation.setText("Dân tộc:");

        inputDay.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        inputDay.setText("dd");

        inputYear.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        inputYear.setText("yyyy");

        inputMonth.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        inputMonth.setText("mm");
        inputMonth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputMonthActionPerformed(evt);
            }
        });

        inputNation.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        labelNoiSinh.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        labelNoiSinh.setText("Nơi sinh:");

        inputNoiSinh.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        labelDiaChi.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        labelDiaChi.setText("Địa chỉ thường trú:");

        inputDiaChi.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        inputDiaChi.setToolTipText("");

        jButton1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton1.setText("ChoseImage");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelChoseLayout = new javax.swing.GroupLayout(panelChose);
        panelChose.setLayout(panelChoseLayout);
        panelChoseLayout.setHorizontalGroup(
            panelChoseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelChoseLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(21, 21, 21))
        );
        panelChoseLayout.setVerticalGroup(
            panelChoseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelChoseLayout.createSequentialGroup()
                .addContainerGap(124, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        jLayeredPane1.add(panelChose);
        panelChose.setBounds(0, 0, 140, 160);

        jLabel1.setText("Label này hiện ảnh, ở mục icon");

        javax.swing.GroupLayout panelPictureLayout = new javax.swing.GroupLayout(panelPicture);
        panelPicture.setLayout(panelPictureLayout);
        panelPictureLayout.setHorizontalGroup(
            panelPictureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelPictureLayout.setVerticalGroup(
            panelPictureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
        );

        jLayeredPane1.add(panelPicture);
        panelPicture.setBounds(0, 0, 140, 160);

        javax.swing.GroupLayout imagePanelLayout = new javax.swing.GroupLayout(imagePanel);
        imagePanel.setLayout(imagePanelLayout);
        imagePanelLayout.setHorizontalGroup(
            imagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
        );
        imagePanelLayout.setVerticalGroup(
            imagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
        );

        labelTinhTrang.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        labelTinhTrang.setText("Tình trạng khai báo:");

        selectTinhTrang.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        selectTinhTrang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Đã khai báo", "Chưa khai báo" }));

        labelCachLy.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        labelCachLy.setText("Tình trạng sức khoẻ:");

        inputCachLy.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        labelThoiGianCachLy.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        labelThoiGianCachLy.setText("Thời gian cách ly:");

        inputTimeCachLy.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        labelMucDo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        labelMucDo.setText("Mức độ cách ly:");

        selectMucDo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        selectMucDo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tại nhà sau khi di chuyển (14 ngày)", "Tập trung tại cơ sở cấp huyện trở xuống", "Cách ly khẩn cấp tại cơ sở y tế", "Chưa cách ly" }));

        labelTest.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        labelTest.setText("Test Covid");

        selectTest.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        selectTest.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lần 1", "Lần 2", "Lần 3" }));

        labelHinhThuc.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        labelHinhThuc.setText("Hình thức:");

        inputHinhThuc.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        labelTimeTest.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        labelTimeTest.setText("Thời gian:");

        inputTimeTest.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        inputTimeTest.setText("dd/mm/yyyy");

        labelKetQua.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        labelKetQua.setText("Kết quả:");

        selectKetQua.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        selectKetQua.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Âm tính", "Dương tính" }));

        labelLichTrinh.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        labelLichTrinh.setText("Lịch trình di chuyển:");

        showLichTriinh.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        buttomSave.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        buttomSave.setIcon(new javax.swing.ImageIcon("D:\\Workspace\\JAVA\\MyApp\\src\\icon\\Paomedia-Small-N-Flat-Floppy-0.png")); // NOI18N
        buttomSave.setText("Lưu");

        buttomAdd.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        buttomAdd.setIcon(new javax.swing.ImageIcon("D:\\Workspace\\JAVA\\MyApp\\src\\icon\\Icojam-Blue-Bits-Math-add-0.png")); // NOI18N
        buttomAdd.setText("Thêm lịch trình");

        buttomView.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        buttomView.setIcon(new javax.swing.ImageIcon("D:\\Workspace\\JAVA\\MyApp\\src\\icon\\view-icon.png")); // NOI18N
        buttomView.setText("Xem lịch trình");

        buttomExit.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        buttomExit.setIcon(new javax.swing.ImageIcon("D:\\Workspace\\JAVA\\MyApp\\src\\icon\\Awicons-Vista-Artistic-Delete-0.png")); // NOI18N
        buttomExit.setText("Thoát");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttomAdd)
                .addGap(18, 18, 18)
                .addComponent(buttomView)
                .addGap(18, 18, 18)
                .addComponent(buttomSave)
                .addGap(18, 18, 18)
                .addComponent(buttomExit)
                .addGap(23, 23, 23))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(showLichTriinh)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(labelTinhTrang)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(selectTinhTrang, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(labelTest)
                                        .addGap(18, 18, 18))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(labelTimeTest)
                                        .addGap(30, 30, 30)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(selectTest, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(18, 18, 18)
                                        .addComponent(labelHinhThuc))
                                    .addComponent(inputTimeTest))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(labelCachLy)
                                .addGap(18, 18, 18)
                                .addComponent(inputCachLy))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(inputHinhThuc, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(labelKetQua)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(selectKetQua, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(labelMucDo)
                        .addGap(26, 26, 26)
                        .addComponent(selectMucDo, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(labelThoiGianCachLy)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(inputTimeCachLy))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(labelLichTrinh)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(labelDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(inputDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(labelNoiSinh)
                                .addGap(18, 18, 18)
                                .addComponent(inputNoiSinh, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(labelName)
                                        .addGap(26, 26, 26)
                                        .addComponent(inputName, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(ID)
                                        .addGap(26, 26, 26)
                                        .addComponent(inputID, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(birthday)
                                        .addGap(26, 26, 26)
                                        .addComponent(inputDay, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(inputMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(inputYear, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(labelNation)))
                                .addGap(28, 28, 28)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(labelSex)
                                            .addComponent(labelReligion))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(selectSex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(inputReligion, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(inputNation, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addComponent(imagePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelName)
                            .addComponent(inputName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelSex)
                            .addComponent(selectSex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ID)
                            .addComponent(inputID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelReligion)
                            .addComponent(inputReligion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(birthday)
                            .addComponent(inputDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelNation)
                            .addComponent(inputNation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelNoiSinh)
                            .addComponent(inputNoiSinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelDiaChi)
                            .addComponent(inputDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(imagePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(selectTinhTrang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labelCachLy)
                        .addComponent(inputCachLy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(labelTinhTrang))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelMucDo)
                    .addComponent(selectMucDo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelThoiGianCachLy)
                    .addComponent(inputTimeCachLy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTest)
                    .addComponent(selectTest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelHinhThuc)
                    .addComponent(inputHinhThuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTimeTest)
                    .addComponent(inputTimeTest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelKetQua)
                    .addComponent(selectKetQua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(labelLichTrinh)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(showLichTriinh, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttomExit)
                    .addComponent(buttomSave)
                    .addComponent(buttomView)
                    .addComponent(buttomAdd))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void inputMonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputMonthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputMonthActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        panelChose.setVisible(false);
        panelPicture.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ID;
    private javax.swing.JLabel birthday;
    private javax.swing.JButton buttomAdd;
    private javax.swing.JButton buttomExit;
    private javax.swing.JButton buttomSave;
    private javax.swing.JButton buttomView;
    private javax.swing.JPanel imagePanel;
    private javax.swing.JTextField inputCachLy;
    private javax.swing.JTextField inputDay;
    private javax.swing.JTextField inputDiaChi;
    private javax.swing.JTextField inputHinhThuc;
    private javax.swing.JTextField inputID;
    private javax.swing.JTextField inputMonth;
    private javax.swing.JTextField inputName;
    private javax.swing.JTextField inputNation;
    private javax.swing.JTextField inputNoiSinh;
    private javax.swing.JTextField inputReligion;
    private javax.swing.JTextField inputTimeCachLy;
    private javax.swing.JTextField inputTimeTest;
    private javax.swing.JTextField inputYear;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelCachLy;
    private javax.swing.JLabel labelDiaChi;
    private javax.swing.JLabel labelHinhThuc;
    private javax.swing.JLabel labelKetQua;
    private javax.swing.JLabel labelLichTrinh;
    private javax.swing.JLabel labelMucDo;
    private javax.swing.JLabel labelName;
    private javax.swing.JLabel labelNation;
    private javax.swing.JLabel labelNoiSinh;
    private javax.swing.JLabel labelReligion;
    private javax.swing.JLabel labelSex;
    private javax.swing.JLabel labelTest;
    private javax.swing.JLabel labelThoiGianCachLy;
    private javax.swing.JLabel labelTimeTest;
    private javax.swing.JLabel labelTinhTrang;
    private javax.swing.JPanel panelChose;
    private javax.swing.JPanel panelPicture;
    private javax.swing.JComboBox<String> selectKetQua;
    private javax.swing.JComboBox<String> selectMucDo;
    private javax.swing.JComboBox<String> selectSex;
    private javax.swing.JComboBox<String> selectTest;
    private javax.swing.JComboBox<String> selectTinhTrang;
    private javax.swing.JTextField showLichTriinh;
    // End of variables declaration//GEN-END:variables
}
